name: 电视家
on:
  workflow_dispatch:
  schedule:
     - cron: '3 0-14/1 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id		  
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/YiBai12/JS.git ~/JS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/JS
          git checkout main
          npm install
      - name: '运行 【电视家】'
        run: |
          cd ~/JS
          node Task/dsj.js
        env: 
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

